### ISSUE TITLE
V25 is no longer behind a bc-insider secret. 

### ISSUE THREAD

**Issue by rdebath** [StefanMaron/Dyn365BCSandbox.Code.History#2]
As V25 is no longer behind a bc-insider secret would you considered including it in the public code history repository ?

**Comment by StefanMaron** [comment]
This repo includes branches for Next Minor and Next Major versions, you can go to the branch overview and search for `-vNext`
https://github.com/StefanMaron/MSDyn365BC.Sandbox.Code.History/branches/all?query=-vNext

**Comment by rdebath** [comment]
WAT!
Oh, I though this repo was just the scripts ... now I'm confused what the difference is between the two repos  ... they look rather different.
