### ISSUE TITLE
Renaming file paths

### ISSUE THREAD

**Issue by gntpet** [StefanMaron/Dyn365BCSandbox.Code.History#3]
Hey @StefanMaron , 

Just want to bring to your attention, that there's some strange commits that just rename the files back and fort. 

I noticed it while looking at the file history of FindRecordManagement.Codeunit.al

The last 6 commits it just renames files back and forth:

72d1d1a480b673b96fb9c3e809ff3abe34a633f6
rename from baseapp/source/Base Application/Utilities/FindRecordManagement.Codeunit.al
rename to BaseApp/Source/Base Application/Utilities/FindRecordManagement.Codeunit.al

08f96e30deb09e79f1cfb65e82fbc721e7e1ac81
rename from BaseApp/Source/Base Application/Utilities/FindRecordManagement.Codeunit.al
rename to baseapp/source/Base Application/Utilities/FindRecordManagement.Codeunit.al

![image](https://github.com/user-attachments/assets/08e6e08a-d5b5-48c2-a04a-6cc0bb65d5b5)

Best Regards & Big thanks for maintaining this repo
Gintautas

**Comment by StefanMaron** [comment]
Thanks! But I am just extracting the Artifacts how Microsoft provides them. 
Seems like they are moving stuff around then.

If you want to have a bit more stable commit you should check out the other Repo, which uses the OnPrem Artifacts and updates only once per month:

https://github.com/StefanMaron/MSDyn365BC.Code.History

**Comment by jwikman** [comment]
This change might absolutely come from the artifacts, but maybe it's worth to patch the folder names to a consistent casing, to avoid all those unnecessary rename commits?

I.e. always use `BaseApp/Source`, even if the artifact says `baseapp/source`
